(function(root,factory){'use strict';const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.FantasyHQTeamFitV1=api;})(typeof window!=='undefined'?window:globalThis,function(){
  'use strict';
  const STATUS=Object.freeze({STRONG_FIT:'STRONG_FIT',GOOD_FIT:'GOOD_FIT',NEUTRAL_FIT:'NEUTRAL_FIT',POOR_FIT:'POOR_FIT',REDUNDANT:'REDUNDANT'});
  const NEED=Object.freeze({CRITICAL:4,HIGH:3,MODERATE:2,LOW:1,NONE:0});
  const STARTER_PATH=Object.freeze({IMMEDIATE:'IMMEDIATE',COMPETITIVE:'COMPETITIVE',DEPTH_ONLY:'DEPTH_ONLY',BLOCKED:'BLOCKED',UNKNOWN:'UNKNOWN'});
  const clean=value=>String(value??'').trim();
  const finite=value=>value!==''&&value!==null&&value!==undefined&&Number.isFinite(Number(value))?Number(value):null;
  const clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,Number(value)||0));
  const position=value=>{const p=clean(value).toUpperCase().replace(/[^A-Z]/g,'');return p==='DEF'||p==='DST'||p==='DEFENSE'?'DST':p;};
  const rosterSlot=value=>{const raw=clean(typeof value==='object'?value.position:value).toUpperCase().replace(/[^A-Z0-9/]/g,''),base=raw.replace(/\d+$/,'');if(['DEF','D/ST'].includes(base))return'DST';if(['BENCH','BE'].includes(base))return'BN';if(['W/R/T','WR/RB/TE','RB/WR/TE','FLEX'].includes(base))return'FLEX';return base;};
  const identityId=player=>clean(player?.identity?.canonicalPlayerId||player?.canonicalPlayerId||player?.playerId||player?.yahooPlayerId||player?.id);
  const scoringKey=value=>{const text=clean(value).toLowerCase();if(text.includes('full')||text==='ppr')return'full-ppr';if(text.includes('half'))return'half-ppr';if(text.includes('standard')||text.includes('non'))return'standard';return text||'unknown';};
  const evidenceOf=player=>player?.teamFitEvidence||player?.seasonEvidence?.teamFit||player?.raw?.teamFitEvidence||{};
  const sourceEvidence=player=>{const direct=evidenceOf(player),start=player?.startSitEvidence||{},waiver=player?.waiverEvidence||{};return{...direct,role:finite(direct.role)??finite(start.role)??finite(waiver.role),opportunity:finite(direct.opportunity)??finite(start.opportunity)??finite(waiver.opportunity),upside:finite(direct.upside)??finite(start.upside)??finite(waiver.upside),confidence:finite(direct.confidence)??finite(start.confidence)??finite(waiver.confidence),injuryUncertainty:finite(direct.injuryUncertainty)??finite(start.injuryUncertainty),replaceability:finite(direct.replaceability)??finite(waiver.replaceability)}};
  const levelName=value=>Object.keys(NEED).find(key=>NEED[key]===value)||'NONE';
  function configuredSlots(model,profile){const source=model?.snapshot?.settings?.rosterSlots||profile?.settings?.rosterSlots||[];if(Array.isArray(source)&&source.length)return source.flatMap(value=>{if(value&&typeof value==='object'){const count=Math.max(1,Number(value.count)||1);return Array.from({length:count},()=>rosterSlot(value));}return[rosterSlot(value)]});const settings=profile?.settings||{};return[['QB',settings.startQB],['RB',settings.startRB],['WR',settings.startWR],['TE',settings.startTE],['FLEX',settings.flex],['K',settings.startK],['DST',settings.startDST],['BN',settings.bench],['IR',settings.irSlots]].flatMap(([name,count])=>Array.from({length:Math.max(0,Number(count)||0)},()=>name));}
  function trustworthy(model){if(model?.draftSnapshot)return{ok:false,reason:'Current Yahoo roster is unavailable; Draft Snapshot cannot authorize production TeamFit.'};if(!model?.demo&&clean(model?.sourceLabel).toLowerCase()!=='yahoo')return{ok:false,reason:'Current Yahoo roster state is required.'};if(model?.userTeamResolution?.status!=='RESOLVED')return{ok:false,reason:'Current roster ownership is unresolved.'};if(!Array.isArray(model?.roster)||!model.roster.length)return{ok:false,reason:'Current roster is unavailable.'};if(model?.stale||model?.snapshot?.datasets?.players?.status==='STALE')return{ok:false,reason:'Current roster evidence is stale.'};return{ok:true,reason:null};}
  function eligiblePositions(player){const evidence=evidenceOf(player),declared=Array.isArray(evidence.eligiblePositions)?evidence.eligiblePositions.map(position).filter(Boolean):[],primary=position(player?.position);return Object.freeze([...new Set(declared.length?declared:[primary])]);}
  function quality(player,scoringFormat){const evidence=sourceEvidence(player),role=finite(evidence.role),opportunity=finite(evidence.opportunity),upside=finite(evidence.upside),formatFit=finite(evidence?.scoringFitByFormat?.[scoringKey(scoringFormat)])??finite(evidence.scoringFit),known=[role,opportunity,upside,formatFit].filter(value=>value!==null);return known.length?known.reduce((sum,value)=>sum+value,0)/known.length:null;}
  function isUnavailable(player){return['OUT','IR','PUP','NFI','SUSP'].includes(clean(player?.injuryStatus).toUpperCase());}
  function isFragile(player){const evidence=sourceEvidence(player),uncertainty=finite(evidence.injuryUncertainty);return isUnavailable(player)||(uncertainty!==null&&uncertainty>=55)||clean(evidence.roleStability).toUpperCase()==='UNSTABLE';}
  function rosterContext({model,profile,roster=model?.roster||[]}={}){
    const slots=configuredSlots(model,profile),starterSlots=slots.filter(value=>!['BN','IR'].includes(value)),benchCapacity=slots.filter(value=>value==='BN').length,flexSlots=starterSlots.filter(value=>value==='FLEX').length,format=model?.scoring||profile?.settings?.scoring,positions=['QB','RB','WR','TE','K','DST'],byPosition={};
    positions.forEach(pos=>{const required=starterSlots.filter(value=>value===pos).length,players=roster.filter(player=>eligiblePositions(player).includes(pos)),evaluated=players.filter(player=>quality(player,format)!==null),usable=players.filter(player=>!isUnavailable(player)&&quality(player,format)!==null&&quality(player,format)>=58),strong=players.filter(player=>!isUnavailable(player)&&quality(player,format)!==null&&quality(player,format)>=72),fragile=players.filter(isFragile),bench=players.filter(player=>['BN','BE','IR'].includes(rosterSlot(player?.rosterSlot)));let need=NEED.NONE;if(required&&!players.length)need=NEED.CRITICAL;else if(required&&players.length<required)need=NEED.HIGH;else if(required&&fragile.some(player=>!bench.includes(player)))need=NEED.HIGH;else if(required&&evaluated.length<required)need=NEED.MODERATE;else if(required&&usable.length<required)need=NEED.HIGH;else if(required&&usable.length===required)need=NEED.MODERATE;else if(required&&strong.length<=required)need=NEED.LOW;else if(!required&&players.length===0)need=NEED.NONE;byPosition[pos]=Object.freeze({position:pos,required,total:players.length,evaluated:evaluated.length,unknownQuality:players.length-evaluated.length,usable:usable.length,strong:strong.length,bench:bench.length,fragile:fragile.length,needLevel:levelName(need),needScore:need,players:Object.freeze(players.slice())});});
    const ordered=Object.values(byPosition).filter(item=>item.required).sort((a,b)=>b.needScore-a.needScore||a.position.localeCompare(b.position)),primaryNeed=ordered[0]||null,strongest=ordered.slice().sort((a,b)=>b.strong-a.strong||a.needScore-b.needScore||a.position.localeCompare(b.position))[0]||null,fragilityCount=ordered.reduce((sum,item)=>sum+item.fragile,0),fragility=fragilityCount>=2?'HIGH':fragilityCount===1?'MODERATE':'LOW';return Object.freeze({status:'EVALUATED',slots:Object.freeze(slots),starterSlots:Object.freeze(starterSlots),benchCapacity,flexSlots,byPosition:Object.freeze(byPosition),primaryNeed,strongest,fragility,fragilityCount,rosterSize:roster.length});
  }
  function replaceability(candidate,model){const positions=eligiblePositions(candidate),targetQuality=quality(candidate,model?.scoring),available=Array.isArray(model?.available)?model.available:[];if(!available.length||targetQuality===null)return{value:'UNKNOWN',comparableCount:null};const comparable=available.filter(player=>identityId(player)!==identityId(candidate)&&eligiblePositions(player).some(pos=>positions.includes(pos))&&quality(player,model?.scoring)!==null&&quality(player,model?.scoring)>=targetQuality-6).length;return{value:comparable>=3?'HIGH_REPLACEABILITY':comparable>=1?'MODERATE_REPLACEABILITY':'LOW_REPLACEABILITY',comparableCount:comparable};}
  function insurance(candidate,roster){const evidence=evidenceOf(candidate),target=clean(evidence.insuranceFor),confidence=finite(evidence.insuranceConfidence);if(!target)return{value:'UNKNOWN',target:null};const starter=roster.find(player=>identityId(player)===target);if(!starter||confidence===null||confidence<70)return{value:'UNKNOWN',target:target||null};const role=clean(evidence.insuranceRole).toUpperCase(),fragile=isFragile(starter);if(role==='DIRECT_BACKUP'&&fragile&&confidence>=85)return{value:'HIGH',target};if(role==='DIRECT_BACKUP'||fragile)return{value:'MODERATE',target};return{value:'LOW',target};}
  function provenance(candidate){const evidence=evidenceOf(candidate);return Object.freeze({rosterSource:clean(evidence.rosterSource)||'Yahoo',roleSource:clean(evidence.roleSource)||null,opportunitySource:clean(evidence.opportunitySource)||null,injurySource:clean(evidence.injurySource)||null,relationshipSource:clean(evidence.relationshipSource)||null,availabilitySource:clean(evidence.availabilitySource)||null,fetchedAt:clean(evidence.fetchedAt)||null});}
  function insufficient(reason,model,candidate){return Object.freeze({status:'INSUFFICIENT_VALIDATED_SEASON_DATA',reason,candidateId:identityId(candidate)||null,needLevel:null,starterPath:STARTER_PATH.UNKNOWN,depthImpact:null,flexUtility:null,benchUtility:null,injuryInsurance:null,replaceability:null,riskFlags:Object.freeze([]),strengths:Object.freeze([]),weaknesses:Object.freeze([]),summary:reason,confidence:null,provenance:provenance(candidate||{}),components:null,profileId:model?.profileId||null});}
  function evaluateCandidate({model,profile,candidate}={}){
    const gate=trustworthy(model);if(!gate.ok)return insufficient(gate.reason,model,candidate);if(!candidate||!identityId(candidate))return insufficient('Candidate identity is unresolved.',model,candidate);const context=rosterContext({model,profile}),positions=eligiblePositions(candidate),eligibleContexts=positions.map(pos=>context.byPosition[pos]).filter(Boolean).sort((a,b)=>b.needScore-a.needScore),need=eligibleContexts[0]||null,candidateQuality=quality(candidate,model?.scoring||profile?.settings?.scoring),currentPlayers=eligibleContexts.flatMap(item=>item.players).filter(player=>identityId(player)!==identityId(candidate)),currentStarters=currentPlayers.filter(player=>!['BN','BE','IR'].includes(rosterSlot(player?.rosterSlot))),currentQualities=currentStarters.map(player=>quality(player,model?.scoring||profile?.settings?.scoring)).filter(value=>value!==null),weakestStarter=currentQualities.length?Math.min(...currentQualities):null,evidence=sourceEvidence(candidate),confidence=finite(evidence.confidence),flexEligible=positions.some(pos=>['RB','WR','TE'].includes(pos))&&context.flexSlots>0,insuranceValue=insurance(candidate,model.roster),replacement=replaceability(candidate,model);if(candidateQuality===null||confidence===null)return insufficient('Candidate role, opportunity, upside, or confidence evidence is incomplete.',model,candidate);
    let starterPath;if(need?.required&&need.usable<need.required)starterPath=STARTER_PATH.IMMEDIATE;else if(weakestStarter===null)starterPath=need?.required?STARTER_PATH.COMPETITIVE:STARTER_PATH.DEPTH_ONLY;else if(candidateQuality>=weakestStarter+8)starterPath=STARTER_PATH.IMMEDIATE;else if(candidateQuality>=weakestStarter-4)starterPath=STARTER_PATH.COMPETITIVE;else if(need?.needScore>=NEED.MODERATE||flexEligible)starterPath=STARTER_PATH.DEPTH_ONLY;else starterPath=STARTER_PATH.BLOCKED;
    const redundancyCount=currentPlayers.filter(player=>{const q=quality(player);return q!==null&&q>=candidateQuality-4}).length,redundant=(starterPath===STARTER_PATH.BLOCKED)||(redundancyCount>=2&&need?.needScore<=NEED.LOW),depthImpact=starterPath===STARTER_PATH.IMMEDIATE||need?.needScore>=NEED.HIGH?'STRONG_POSITIVE':starterPath===STARTER_PATH.COMPETITIVE||need?.needScore===NEED.MODERATE?'POSITIVE':redundant?'NEGATIVE':'NEUTRAL',flexUtility=!flexEligible?'NONE':context.flexSlots>=2&&candidateQuality>=65?'HIGH':candidateQuality>=65?'MODERATE':'LOW',benchUtility=clean(evidence.benchUtility).toUpperCase()|| (starterPath===STARTER_PATH.DEPTH_ONLY?'MODERATE':starterPath===STARTER_PATH.BLOCKED?'LOW':'HIGH'),riskFlags=[],strengths=[],weaknesses=[];if(need?.needScore>=NEED.HIGH)strengths.push(`Addresses ${need.position} need`);if(starterPath===STARTER_PATH.IMMEDIATE)strengths.push('Immediate starting path');if(depthImpact==='STRONG_POSITIVE')strengths.push('Meaningful depth improvement');if(flexUtility==='HIGH')strengths.push('High flex utility');if(insuranceValue.value==='HIGH')strengths.push('Validated injury insurance');if(redundant){riskFlags.push('ROLE_REDUNDANCY');weaknesses.push('Duplicates existing roster utility');}if(isFragile(candidate)){riskFlags.push('PLAYER_FRAGILITY');weaknesses.push('Player role or availability is fragile');}if(replacement.value==='HIGH_REPLACEABILITY')weaknesses.push('Comparable replacements are available');if(!strengths.length)strengths.push('Adds roster competition without displacing a protected role');
    const fitScore=clamp((need?.needScore||0)*16+(starterPath===STARTER_PATH.IMMEDIATE?28:starterPath===STARTER_PATH.COMPETITIVE?18:starterPath===STARTER_PATH.DEPTH_ONLY?8:-8)+(depthImpact==='STRONG_POSITIVE'?14:depthImpact==='POSITIVE'?8:depthImpact==='NEGATIVE'?-10:0)+(flexUtility==='HIGH'?8:flexUtility==='MODERATE'?4:0)+(insuranceValue.value==='HIGH'?8:insuranceValue.value==='MODERATE'?4:0)-(redundant?18:0)),status=redundant?STATUS.REDUNDANT:fitScore>=72?STATUS.STRONG_FIT:fitScore>=52?STATUS.GOOD_FIT:fitScore>=32?STATUS.NEUTRAL_FIT:STATUS.POOR_FIT,summary=status===STATUS.REDUNDANT?`${candidate.name} largely duplicates stronger or similar roster utility.`:starterPath===STARTER_PATH.IMMEDIATE?`${candidate.name} has an immediate path to improve a ${need?.position||position(candidate.position)} starting slot.`:starterPath===STARTER_PATH.COMPETITIVE?`${candidate.name} can compete for a starting or flex role on this roster.`:starterPath===STARTER_PATH.DEPTH_ONLY?`${candidate.name} improves depth but does not currently displace a starter.`:`${candidate.name} has no clear path past the roster's current options.`;
    return Object.freeze({status,reason:null,candidateId:identityId(candidate),needLevel:need?.needLevel||'NONE',starterPath,depthImpact,flexUtility,benchUtility,injuryInsurance:insuranceValue.value,replaceability:replacement.value,riskFlags:Object.freeze(riskFlags),strengths:Object.freeze(strengths),weaknesses:Object.freeze(weaknesses),summary,confidence:clamp(confidence),provenance:provenance(candidate),components:Object.freeze({fitScore,candidateQuality,redundancyCount,comparableReplacementCount:replacement.comparableCount,eligiblePositions:positions,positionContext:need,rosterFragility:context.fragility,flexSlots:context.flexSlots}),profileId:model.profileId});
  }
  function summarize({model,profile}={}){const gate=trustworthy(model);if(!gate.ok)return Object.freeze({status:'INSUFFICIENT_VALIDATED_SEASON_DATA',reason:gate.reason,strongestArea:null,primaryNeed:null,rosterFragility:null,context:null});const context=rosterContext({model,profile});return Object.freeze({status:'EVALUATED',reason:null,strongestArea:context.strongest?.position||null,primaryNeed:context.primaryNeed?.position||null,primaryNeedLevel:context.primaryNeed?.needLevel||'NONE',rosterFragility:context.fragility,context});}
  function compareRosters({model,profile,currentRoster,proposedRoster}={}){const gate=trustworthy(model);if(!gate.ok)return Object.freeze({status:'INSUFFICIENT_VALIDATED_SEASON_DATA',reason:gate.reason});const before=rosterContext({model,profile,roster:currentRoster}),after=rosterContext({model,profile,roster:proposedRoster}),needValue=context=>Object.values(context.byPosition).reduce((sum,item)=>sum+item.needScore,0),usable=context=>Object.values(context.byPosition).reduce((sum,item)=>sum+item.usable,0),beforeNeed=needValue(before),afterNeed=needValue(after),beforeUsable=usable(before),afterUsable=usable(after),fragilityDelta=after.fragilityCount-before.fragilityCount,needDelta=beforeNeed-afterNeed,depthDelta=afterUsable-beforeUsable,improved=needDelta>0||depthDelta>0||fragilityDelta<0,degraded=needDelta<0||depthDelta<0||fragilityDelta>0;return Object.freeze({status:'EVALUATED',before,after,starterImprovement:needDelta>0?'POSITIVE':needDelta<0?'NEGATIVE':'NEUTRAL',depthChange:depthDelta,fragilityChange:fragilityDelta,redundancyChange:'UNSCORED',flexUtilityChange:after.flexSlots-before.flexSlots,positionalNeedChange:needDelta,replaceabilityChange:'UNSCORED',outcome:improved&&!degraded?'IMPROVED':degraded&&!improved?'DEGRADED':'MIXED_OR_NEUTRAL'});}
  return Object.freeze({STATUS,NEED,STARTER_PATH,position,rosterSlot,configuredSlots,trustworthy,eligiblePositions,quality,isFragile,rosterContext,evaluateCandidate,summarize,compareRosters});
});
