(function(root,factory){'use strict';const api=factory(root.FantasyHQYahooSeason);if(typeof module!=='undefined'&&module.exports)module.exports=api;root.FantasyHQYahooSync=api;})(typeof window!=='undefined'?window:globalThis,function(Season){
  'use strict';
  const DEFAULT_BRIDGE='https://localhost:8787';
  const SYNC_SENTINELS=Object.freeze(['leagueKey','fetchedAt','teamRosters','players','errors']);
  const record=value=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
  function validSyncBundle(value){return record(value)&&typeof value.leagueKey==='string'&&value.leagueKey.trim()!==''&&typeof value.fetchedAt==='string'&&value.fetchedAt.trim()!==''&&record(value.teamRosters)&&record(value.players)&&record(value.errors);}
  function responseMetadata(response,text,parsed){const keys=record(parsed)?Object.keys(parsed).sort():[],trimmed=String(text||'').trimStart();return{status:Number(response?.status)||0,ok:Boolean(response?.ok),url:String(response?.url||''),redirected:Boolean(response?.redirected),contentType:String(response?.headers?.get?.('content-type')||''),rawBytes:typeof TextEncoder!=='undefined'?new TextEncoder().encode(String(text||'')).length:String(text||'').length,firstNonWhitespace:trimmed?trimmed[0]:null,topLevelType:Array.isArray(parsed)?'array':parsed===null?'null':typeof parsed,topLevelKeys:keys,sentinels:Object.fromEntries(SYNC_SENTINELS.map(key=>[key,Object.prototype.hasOwnProperty.call(parsed||{},key)])),validSyncBundle:validSyncBundle(parsed)};}
  function logResponseMetadata(metadata){console.info?.('[Yahoo Sync] response_metadata',JSON.stringify(metadata));}
  function createTransport({baseUrl=DEFAULT_BRIDGE,fetchImpl=globalThis.fetch,timeoutMs=45000}={}){
    if(typeof fetchImpl!=='function')throw new Error('Fetch is unavailable');
    async function request(path,options={}){const controller=typeof AbortController==='function'?new AbortController():null,timer=controller&&Number(timeoutMs)>0?setTimeout(()=>controller.abort(),Number(timeoutMs)):null;try{const response=await fetchImpl(`${baseUrl}${path}`,{cache:'no-store',credentials:'omit',...options,signal:options.signal||controller?.signal});let body=null,text='';try{text=typeof response.text==='function'?await response.text():JSON.stringify(await response.json());body=JSON.parse(text);}catch(_){const metadata=responseMetadata(response,text,null);logResponseMetadata(metadata);throw Object.assign(new Error('Yahoo bridge returned invalid JSON.'),{status:response.status,classification:'PARSER_RESPONSE_SHAPE_FAILURE',responseMetadata:metadata,reconnectRequired:false});}const metadata=responseMetadata(response,text,body);logResponseMetadata(metadata);if(!response.ok)throw Object.assign(new Error(body.error||`Yahoo bridge failed (${response.status})`),{status:response.status,classification:body.classification||'BRIDGE_FAILURE',yahooHttpStatus:body.yahooHttpStatus??null,yahooErrorCode:body.yahooErrorCode||null,responseMetadata:metadata,reconnectRequired:Boolean(body.reconnectRequired)});if(path.startsWith('/api/yahoo/sync')&&!validSyncBundle(body))throw Object.assign(new Error('Yahoo bridge returned an invalid sync response shape.'),{status:response.status,classification:'PARSER_RESPONSE_SHAPE_FAILURE',responseMetadata:metadata,reconnectRequired:false});return body;}catch(error){if(controller?.signal.aborted&&!options.signal)throw Object.assign(new Error('Yahoo bridge timed out; the previous valid snapshot remains available.'),{classification:'BRIDGE_TIMEOUT',reconnectRequired:false});throw error;}finally{if(timer)clearTimeout(timer);}}
    return Object.freeze({baseUrl,status:()=>request('/api/yahoo/status'),connectUrl:`${baseUrl}/api/yahoo/connect`,disconnect:()=>request('/api/yahoo/disconnect',{method:'POST'}),discover:(season=2026)=>request(`/api/yahoo/leagues?season=${encodeURIComponent(season)}`),sync:leagueKey=>request(`/api/yahoo/sync?league_key=${encodeURIComponent(leagueKey)}`)});
  }
  function createController({transport,storage,seasonApi=Season,clock=()=>new Date().toISOString()}={}){
    if(!seasonApi)throw new Error('Yahoo season model is unavailable');const store=seasonApi.createStore(storage);
    async function discover(season=2026){const response=await transport.discover(season);return {fetchedAt:response.fetchedAt,leagues:seasonApi.normalizeLeagueList(response.raw||response,{season})};}
    function mapLeague(profile,league){if(!profile?.id||!league?.leagueKey)throw new Error('Explicit profile and Yahoo league selection are required');const current=store.read(profile.id)||{};return store.write(profile.id,{...current,mapping:{provider:'Yahoo',leagueKey:league.leagueKey,leagueName:league.name,season:league.season,confirmedAt:clock(),explicitlyConfirmed:true},sync:{...(current.sync||{}),status:'MAPPED'}});}
    function preserveFailedSubsystems(previous,next){if(!previous)return next;const errors=next.subsystemErrors||{},copy={...next,datasets:{...(next.datasets||{})}};const groups={settings:['settings','settingsReconciliation'],teams:['teams','userTeamKey','currentRoster','identitySummary','ownership'],players:['availablePlayers','ownership','identitySummary'],transactions:['transactions'],standings:['standings'],matchups:['matchups'],liveWeek:['liveWeek']};Object.entries(groups).forEach(([errorKey,fields])=>{const failed=Object.keys(errors).some(key=>key===errorKey||key.startsWith(`${errorKey}:`)||(errorKey==='teams'&&key.startsWith('roster:')));if(failed){fields.forEach(field=>{if(previous[field]!==undefined)copy[field]=previous[field];});if(copy.datasets[errorKey])copy.datasets[errorKey]={...copy.datasets[errorKey],lastSuccessfulSyncAt:previous.datasets?.[errorKey]?.lastSuccessfulSyncAt||null,status:'STALE'};}});return copy;}
    async function sync({profile,canonicalPlayers,aliases,archives}){const current=store.read(profile.id);if(!current?.mapping?.explicitlyConfirmed)throw new Error('Confirm a Yahoo league mapping before syncing');try{const bundle=await transport.sync(current.mapping.leagueKey);const built=seasonApi.buildSeasonSnapshot(bundle,{profile,canonicalPlayers,aliases,archives}),snapshot=preserveFailedSubsystems(current.snapshot,built),syncStatus=Object.keys(snapshot.subsystemErrors).length?'PARTIAL':'CURRENT',checkpoint=seasonApi.checkpointFromSnapshot(snapshot,{syncStatus}),checkpoints=[...(current.checkpoints||[]),checkpoint].filter(Boolean);return store.write(profile.id,{...current,mapping:{...current.mapping,yahooTeamKey:snapshot.userTeamKey||current.mapping.yahooTeamKey||null},snapshot,checkpoints,sync:{status:syncStatus,lastAttemptAt:clock(),lastSuccessfulSyncAt:clock(),error:null}});}catch(error){if(error?.code!=='YAHOO_SEASON_STORAGE_QUOTA')store.preserveFailure(profile.id,error.message,clock());throw error;}}
    return Object.freeze({status:()=>transport.status(),connectUrl:transport.connectUrl||null,discover,mapLeague,sync,disconnect:()=>transport.disconnect(),read:profileId=>store.read(profileId),store});
  }
  return Object.freeze({DEFAULT_BRIDGE,SYNC_SENTINELS,validSyncBundle,responseMetadata,createTransport,createController});
});
