(function(root,factory){'use strict';const api=factory(root.FantasyHQYahooSeason);if(typeof module!=='undefined'&&module.exports)module.exports=api;root.FantasyHQYahooSync=api;})(typeof window!=='undefined'?window:globalThis,function(Season){
  'use strict';
  const DEFAULT_BRIDGE='https://localhost:8787';
  function createTransport({baseUrl=DEFAULT_BRIDGE,fetchImpl=globalThis.fetch}={}){
    if(typeof fetchImpl!=='function')throw new Error('Fetch is unavailable');
    async function request(path,options={}){const response=await fetchImpl(`${baseUrl}${path}`,{cache:'no-store',credentials:'omit',...options});let body={};try{body=await response.json();}catch(_){body={error:'Yahoo bridge returned invalid JSON',classification:'PARSER_RESPONSE_SHAPE_FAILURE'};}if(!response.ok)throw Object.assign(new Error(body.error||`Yahoo bridge failed (${response.status})`),{status:response.status,classification:body.classification||'BRIDGE_FAILURE',yahooHttpStatus:body.yahooHttpStatus??null,yahooErrorCode:body.yahooErrorCode||null,reconnectRequired:Boolean(body.reconnectRequired)});return body;}
    return Object.freeze({baseUrl,status:()=>request('/api/yahoo/status'),connectUrl:`${baseUrl}/api/yahoo/connect`,disconnect:()=>request('/api/yahoo/disconnect',{method:'POST'}),discover:(season=2026)=>request(`/api/yahoo/leagues?season=${encodeURIComponent(season)}`),sync:leagueKey=>request(`/api/yahoo/sync?league_key=${encodeURIComponent(leagueKey)}`)});
  }
  function createController({transport,storage,seasonApi=Season,clock=()=>new Date().toISOString()}={}){
    if(!seasonApi)throw new Error('Yahoo season model is unavailable');const store=seasonApi.createStore(storage);
    async function discover(season=2026){const response=await transport.discover(season);return {fetchedAt:response.fetchedAt,leagues:seasonApi.normalizeLeagueList(response.raw||response,{season})};}
    function mapLeague(profile,league){if(!profile?.id||!league?.leagueKey)throw new Error('Explicit profile and Yahoo league selection are required');const current=store.read(profile.id)||{};return store.write(profile.id,{...current,mapping:{provider:'Yahoo',leagueKey:league.leagueKey,leagueName:league.name,season:league.season,confirmedAt:clock(),explicitlyConfirmed:true},sync:{...(current.sync||{}),status:'MAPPED'}});}
    function preserveFailedSubsystems(previous,next){if(!previous)return next;const errors=next.subsystemErrors||{},copy={...next,datasets:{...(next.datasets||{})}};const groups={settings:['settings','settingsReconciliation'],teams:['teams','userTeamKey','currentRoster','identitySummary','ownership'],players:['availablePlayers','ownership','identitySummary'],transactions:['transactions'],standings:['standings'],matchups:['matchups']};Object.entries(groups).forEach(([errorKey,fields])=>{const failed=Object.keys(errors).some(key=>key===errorKey||key.startsWith(`${errorKey}:`)||(errorKey==='teams'&&key.startsWith('roster:')));if(failed){fields.forEach(field=>{if(previous[field]!==undefined)copy[field]=previous[field];});if(copy.datasets[errorKey])copy.datasets[errorKey]={...copy.datasets[errorKey],lastSuccessfulSyncAt:previous.datasets?.[errorKey]?.lastSuccessfulSyncAt||null,status:'STALE'};}});return copy;}
    async function sync({profile,canonicalPlayers,aliases,archives}){const current=store.read(profile.id);if(!current?.mapping?.explicitlyConfirmed)throw new Error('Confirm a Yahoo league mapping before syncing');try{const bundle=await transport.sync(current.mapping.leagueKey);const built=seasonApi.buildSeasonSnapshot(bundle,{profile,canonicalPlayers,aliases,archives}),snapshot=preserveFailedSubsystems(current.snapshot,built);const snapshots=[...(current.snapshots||[]),snapshot].slice(-14);return store.write(profile.id,{...current,mapping:{...current.mapping,yahooTeamKey:snapshot.userTeamKey||current.mapping.yahooTeamKey||null},snapshot,snapshots,sync:{status:Object.keys(snapshot.subsystemErrors).length?'PARTIAL':'CURRENT',lastAttemptAt:clock(),lastSuccessfulSyncAt:clock(),error:null}});}catch(error){store.preserveFailure(profile.id,error.message,clock());throw error;}}
    return Object.freeze({status:()=>transport.status(),connectUrl:transport.connectUrl||null,discover,mapLeague,sync,disconnect:()=>transport.disconnect(),read:profileId=>store.read(profileId),store});
  }
  return Object.freeze({DEFAULT_BRIDGE,createTransport,createController});
});
