'use strict';
const D=require('../js/jonin-decision-intelligence-v1.js'),S=require('../js/draft-session-v1.js');
function assert(condition,message){if(!condition)throw new Error(message)}
function player(id,name,pos,overall,tier,extra={}){return{id,name,pos,overall,...extra}}
function input(p,overrides={}){return{player:p,mamba:overrides.mamba??85,tier:overrides.tier??'A',overall:p.overall,rosterFitModifier:overrides.fit??0,marketPressure:overrides.pressure??50,survivalRisk:overrides.risk??40,sameTierRemaining:overrides.depth??2,nextTierDrop:overrides.drop??10,expectedReplacementValue:overrides.future??72,positionDepth:overrides.positionDepth??10,round:overrides.round??4}}
const tests=[];const test=(name,fn)=>tests.push([name,fn]);
test('four independent scores are bounded',()=>{const result=D.evaluate(input(player(1,'Alpha','WR',10,'A')));for(const key of ['playerValue','rosterFit','opportunityCost','expectedFutureValue','championship'])assert(result.scores[key]>=0&&result.scores[key]<=100,key)});
test('elite value cannot be overridden by roster need',()=>{const elite=input(player(1,'Elite WR','WR',1),{mamba:99,tier:'S',fit:-2}),need=input(player(2,'Need RB','RB',30),{mamba:76,tier:'B',fit:9});assert(D.choose([need,elite]).recommended[0].playerId===1,'talent gap overridden')});
test('best value best fit and recommendation can differ',()=>{const a=input(player(1,'Value','WR',4),{mamba:94,fit:-1}),b=input(player(2,'Fit','RB',18),{mamba:82,fit:8,pressure:85,risk:75});const out=D.choose([a,b]);assert(out.bestValue.playerId===1,'best value');assert(out.bestTeamFit.playerId===2,'best fit');assert(out.recommended.length===2,'recommended')});
test('environment separates unavailable situation from talent',()=>{const out=D.environment({name:'No Data'});assert(out.status==='UNAVAILABLE'&&out.score===null&&out.talentIndependent,'environment fallback')});
test('evidence metadata and thresholds are explicit',()=>{assert(D.evidenceMetric({value:5,source:'test',confidence:90,verificationStatus:'Verified'}).verificationStatus==='Verified','metadata');assert(D.evidenceAdjustment(1).level==='MINOR','one week');assert(D.evidenceAdjustment(2).level==='MODERATE','two weeks');assert(D.evidenceAdjustment(3).level==='MAJOR','three weeks');assert(D.evidenceAdjustment(0,{structuralChange:true}).level==='MAJOR','structural')});
test('strategy modules remain advisory and pluggable',()=>{const signals=D.strategySignals(input(player(1,'Alpha','TE',12),{tier:'S'}));assert(signals.length===4&&signals.every(signal=>signal.source&&Array.isArray(signal.signals)),'strategies')});
test('league grading produces one rare A plus at most',()=>{const teams=Array.from({length:10},(_,i)=>({team:i+1,value:95-i*3,construction:95-i*2,ceiling:94-i*2,floor:93-i*2,consistency:92-i*2,risk:90-i,playoffOutlook:null,positionalAdvantage:92-i*2,draftEfficiency:93-i*2})),graded=D.gradeLeague(teams);assert(graded.filter(team=>team.grade==='A+').length<=1,'A+ inflation');assert(graded[0].rank===1&&graded[9].rank===10,'ranking')});
test('session saves, resumes and blocks overwrite',()=>{const data=new Map(),storage={getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)},store=new S.DraftSessionStore(storage),state={mode:'live',slot:10,pick:2,drafted:[1],history:[{pick:1,id:1,team:1}],settings:{scoring:'half'},recommendations:[2],importedRankings:[{id:1,overall:1}]};store.start(state);assert(store.load().history.length===1,'resume');let blocked=false;try{store.start(state)}catch(_){blocked=true}assert(blocked,'overwrite allowed');store.save({...state,pick:3,drafted:[1,2],history:[...state.history,{pick:2,id:2,team:2}]});assert(store.load().history.length===2,'after-pick save')});
test('timeline and notebook are deterministic',()=>{const index=new Map([[1,{name:'Alpha'}],[2,{name:'Beta'}]]),timeline=S.timeline([{pick:11,id:2,team:10},{pick:1,id:1,team:1}],index);assert(timeline[0].round===1&&timeline[1].picks[0].label==='2.01','timeline');const data=new Map(),storage={getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value)};S.saveNote('Tier > Need',storage);assert(S.loadNote(storage)==='Tier > Need','note')});
let failed=0;for(const [name,fn] of tests){try{fn()}catch(error){failed++;console.error(`FAIL ${name}: ${error.message}`)}}console.log(`Jōnin 4.0: ${tests.length-failed} passed, ${failed} failed`);if(failed)process.exit(1);
