'use strict';

const STATUSES=Object.freeze(['UNKNOWN','INSUFFICIENT_DATA','EVIDENCE_PRESENT']);
const ARCHETYPES=Object.freeze(['BREAKOUT','ROLE_EXPANSION','CONTINGENT_WORKLOAD','CONTINGENT_BELLCOW','AMBIGUOUS_BACKFIELD','TARGET_EARNER','DEVELOPMENTAL_BREAKOUT','ELITE_TRAIT','MISPRICED_CEILING','LOW_OPTIONALITY']);
const POSITION_SIGNALS=Object.freeze({
  RB:Object.freeze(['snapShare','rushShare','touchShare','targets','targetShare','routes','routeParticipation','receptions','receivingYards','redZoneTouches','goalLineTouches','explosiveRunIndicators','depthChartPosition','starterAhead','contingentRole','ambiguousBackfield','projectedWorkload','age','experience','draftCapital']),
  WR:Object.freeze(['routeParticipation','targets','targetShare','tprr','yprr','firstReadTargetShare','receptions','receivingYards','airYardUsage','redZoneUsage','alignmentRole','age','experience','draftCapital','targetCompetition','roleGrowthIndicators']),
  TE:Object.freeze(['routeParticipation','tprr','yprr','targetShare','firstReadTargetShare','receptions','receivingYards','redZoneUsage','snapShare','blockingRouteContext','age','experience','targetCompetition']),
  QB:Object.freeze(['passAttempts','passingYards','passingTouchdowns','interceptions','designedRushes','scrambles','rushingAttempts','rushingYards','rushingTouchdowns','redZoneRushing','passingEfficiency','age','experience']),
});
const clean=value=>value===undefined||value===null?'':String(value).trim();
const finite=value=>value===undefined||value===null||clean(value)===''?null:(Number.isFinite(Number(value))?Number(value):null);
function iso(value,field){const text=clean(value);if(!text||Number.isNaN(Date.parse(text)))throw new TypeError(`${field} must be an ISO date or timestamp`);return text}
function canonicalPlayerId(player={}){const raw=clean(player.playerId??player.canonicalPlayerId??player.canonicalId??player.id);if(!raw)throw new TypeError('canonical Fantasy HQ player identity is required');return /^fhq_/i.test(raw)?raw:`fhq_player_${raw}`}
function identity(player={}){const position=clean(player.position??player.pos).toUpperCase(),name=clean(player.canonicalName??player.name),team=clean(player.nflTeam??player.team);if(!name||!['RB','WR','TE','QB','K','DST'].includes(position))throw new TypeError('canonical name and supported position are required');const externalIds={...(player.externalIds||{})};[['sleeper',player.sleeperId],['yahoo',player.yahooId],['nfl',player.nflId],['fantasyPros',player.fantasyProsId]].forEach(([provider,value])=>{if(usableId(value))externalIds[provider]=clean(value)});return Object.freeze({playerId:canonicalPlayerId(player),liveCanonicalId:clean(player.canonicalId??player.id)||null,canonicalName:name,position,nflTeam:team||null,externalIds:Object.freeze(externalIds)})}
function usableId(value){return value!==undefined&&value!==null&&clean(value)!==''}
function metric(input={}){const source=clean(input.source),name=clean(input.metric),metricType=clean(input.metricType).toUpperCase(),basis=clean(input.basis??input.temporalBasis).toUpperCase(),matchStatus=clean(input.matchStatus||'MATCHED').toUpperCase(),season=finite(input.season);if(!source||!name)throw new TypeError('metric source and metric are required');if(!['USAGE','ROLE','TRAIT','MARKET','PROJECTION','BIOGRAPHIC','CONTEXT'].includes(metricType))throw new TypeError('unsupported metric type');if(!['HISTORICAL','PROJECTED','CURRENT'].includes(basis))throw new TypeError('metric basis must be historical, projected, or current');if(season===null||season<2000)throw new TypeError('metric season is required');return Object.freeze({metric:name,value:input.value??null,unit:clean(input.unit)||null,source,snapshotDate:iso(input.snapshotDate,'snapshotDate'),season,metricType,basis,sourcePlayerId:clean(input.sourcePlayerId)||null,confidence:clean(input.confidence||'UNKNOWN').toUpperCase(),matchStatus})}
function signal(input={}){const archetype=clean(input.archetype).toUpperCase(),evidence=Object.freeze([...(input.evidence||[])]);if(!ARCHETYPES.includes(archetype))throw new TypeError('unsupported Championship Equity archetype');if(!clean(input.source)||!clean(input.snapshotDate))throw new TypeError('signal provenance is required');return Object.freeze({archetype,evidence,source:clean(input.source),confidence:clean(input.confidence||'UNKNOWN').toUpperCase(),snapshotDate:iso(input.snapshotDate,'snapshotDate'),status:evidence.length?'EVIDENCE_PRESENT':'INSUFFICIENT_DATA'})}
function draftStage(context={}){const round=Math.max(1,finite(context.currentRound)??1),total=Math.max(round,finite(context.totalRounds)??round),remaining=Math.max(0,finite(context.remainingStarterCapacity)??0);if(remaining===0&&round>1)return'BENCH_BUILDING';const progress=round/total;return progress<=1/3?'EARLY':progress<=2/3?'MIDDLE':'LATE'}
function leagueContext(input={}){return Object.freeze({profileId:clean(input.profileId)||null,teamCount:finite(input.teamCount),scoringFormat:clean(input.scoringFormat)||null,starters:Object.freeze({...input.starters}),flexCount:finite(input.flexCount)??0,benchCount:finite(input.benchCount)??0,currentRound:finite(input.currentRound),currentPick:finite(input.currentPick),totalRounds:finite(input.totalRounds),remainingRosterCapacity:finite(input.remainingRosterCapacity),remainingStarterCapacity:finite(input.remainingStarterCapacity),draftStage:draftStage(input)})}
function valueReachContext(input={}){return Object.freeze({currentPick:finite(input.currentPick),expertOverallRank:finite(input.expertOverallRank),expertTier:clean(input.expertTier)||null,positionalRank:finite(input.positionalRank),valueDifference:finite(input.valueDifference),tierDifference:finite(input.tierDifference),draftStage:clean(input.draftStage)||null,guardrailStatus:'NOT_ACTIVE',recommendationAuthority:false})}
function replacementAvailability(input={}){return Object.freeze({status:'UNKNOWN',value:null,active:false,inputs:Object.freeze({leagueSize:finite(input.leagueSize),rosterSize:finite(input.rosterSize),starterCount:finite(input.starterCount),benchCount:finite(input.benchCount),position:clean(input.position)||null,expectedRosteredPlayers:finite(input.expectedRosteredPlayers)})})}
function shadowRecord(input={}){const metrics=Object.freeze([...(input.metrics||[])].map(metric)),signals=Object.freeze([...(input.signals||[])].map(signal)),hasEvidence=metrics.some(item=>item.value!==null)||signals.some(item=>item.status==='EVIDENCE_PRESENT'),context=leagueContext(input.leagueContext||{});return Object.freeze({schemaVersion:'1.0',mode:'SHADOW',recommendationAuthority:false,identity:identity(input.player),status:hasEvidence?'EVIDENCE_PRESENT':'INSUFFICIENT_DATA',evidenceQuality:hasEvidence?'UNASSESSED':'UNKNOWN',ceilingSignal:metrics.some(item=>['TRAIT','PROJECTION'].includes(item.metricType)&&item.value!==null)?'EVIDENCE_PRESENT':'UNKNOWN',pathToCeilingSignal:signals.some(item=>['ROLE_EXPANSION','CONTINGENT_WORKLOAD','CONTINGENT_BELLCOW','BREAKOUT','DEVELOPMENTAL_BREAKOUT'].includes(item.archetype)&&item.status==='EVIDENCE_PRESENT')?'EVIDENCE_PRESENT':'UNKNOWN',contingentValueSignal:signals.some(item=>['CONTINGENT_WORKLOAD','CONTINGENT_BELLCOW'].includes(item.archetype)&&item.status==='EVIDENCE_PRESENT')?'EVIDENCE_PRESENT':'UNKNOWN',breakoutSignal:signals.some(item=>['BREAKOUT','DEVELOPMENTAL_BREAKOUT'].includes(item.archetype)&&item.status==='EVIDENCE_PRESENT')?'EVIDENCE_PRESENT':'UNKNOWN',optionalityContext:signals.some(item=>item.archetype==='LOW_OPTIONALITY'&&item.status==='EVIDENCE_PRESENT')?'EVIDENCE_PRESENT':'UNKNOWN',metrics,archetypes:signals,leagueContext:context,valueReach:valueReachContext({...input.valueReach,draftStage:context.draftStage}),replacementAvailability:replacementAvailability({...input.replacementAvailability,position:input.player?.position??input.player?.pos})})}

module.exports=Object.freeze({STATUSES,ARCHETYPES,POSITION_SIGNALS,canonicalPlayerId,identity,metric,signal,draftStage,leagueContext,valueReachContext,replacementAvailability,shadowRecord});
