#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),usage=require('../js/intelligence-core/historical-usage');
const ROOT=path.resolve(__dirname,'..'),players=JSON.parse(fs.readFileSync(path.join(ROOT,'data/players.json'),'utf8'));
const read=relative=>{try{return JSON.parse(fs.readFileSync(path.join(ROOT,relative),'utf8'))}catch{return null}};
const mapping=read('data/gsis_identity_mapping_2026.json')||{mappings:[],unmatched:[],ambiguous:[],quarantined:[]},historical=read('data/historical_usage_2023_2025.json')||{players:[]};
const classifications=usage.gsisMapping.classifyHistory(players,mapping,historical),positions=['QB','RB','WR','TE'],byPosition={};
for(const pos of positions){const group=classifications.filter(item=>item.position===pos),records=(historical.players||[]).filter(item=>item.position===pos);byPosition[pos]={active:group.length,gsisMapped:group.filter(item=>item.mappedGsis).length,gsisUnmatched:group.filter(item=>!item.mappedGsis).length,ambiguous:(mapping.ambiguous||[]).filter(item=>item.position===pos||item.sourcePosition===pos).length,playersWithHistory:new Set(records.map(item=>String(item.canonicalPlayerId))).size,seasonRecords:records.length,noHistoryExpected:group.filter(item=>item.historyStatus==='NO_HISTORY_EXPECTED').length,historyMissing:group.filter(item=>item.historyStatus==='HISTORY_MISSING').length}}
const metric=(pos,predicate)=>new Set((historical.players||[]).filter(item=>item.position===pos&&predicate(item)).map(item=>String(item.canonicalPlayerId))).size;
const present=(record,field)=>record.stats?.[field]!==null&&record.stats?.[field]!==undefined;
const derived=(record,field)=>record.derivedMetrics?.some(item=>item.metric===field);
const trends=record=>record.trends?.some(item=>item.status==='EVIDENCE_PRESENT');
const mappedActive=new Set((mapping.mappings||[]).map(item=>String(item.canonicalPlayerId)));
const report={generatedAt:new Date().toISOString(),nflverseLiveAccess:'UNAVAILABLE_IN_CODEX_ENVIRONMENT',source:{players:'official nflverse players release',weeklyStats:'official nflverse stats_player_week releases',seasons:[2023,2024,2025],routeParticipation:'DEFERRED_SOURCE_AND_LICENSE_AUDIT'},activePlayers:players.length,skillPlayers:classifications.length,gsisCoverage:{mapped:mappedActive.size,unmatched:players.length-mappedActive.size,sourceRowsUnmatched:mapping.unmatched?.length||0,ambiguous:mapping.ambiguous?.length||0,duplicateProviderIds:(mapping.quarantined||[]).filter(item=>item.reason==='DUPLICATE_GSIS_ID').length,duplicateCanonicalAttachments:(mapping.quarantined||[]).filter(item=>item.reason==='DUPLICATE_CANONICAL_ATTACHMENT').length,byPosition},history:{seasonRecords:historical.players?.length||0,players:new Set((historical.players||[]).map(item=>String(item.canonicalPlayerId))).size,bySeason:Object.fromEntries([2023,2024,2025].map(season=>[season,(historical.players||[]).filter(item=>item.season===season).length])),noHistoryExpected:classifications.filter(item=>item.historyStatus==='NO_HISTORY_EXPECTED').length,historyMissing:classifications.filter(item=>item.historyStatus==='HISTORY_MISSING').length},usageCoverage:{RB:{rushing:metric('RB',r=>present(r,'rushingAttempts')),receiving:metric('RB',r=>present(r,'targets')),touches:metric('RB',r=>derived(r,'totalTouches')),redZone:metric('RB',r=>present(r,'redZoneRushingAttempts')||present(r,'redZoneTargets')),goalLine:metric('RB',r=>present(r,'goalLineCarries')),routes:metric('RB',r=>present(r,'routes')),trends:metric('RB',trends)},WR:{targets:metric('WR',r=>present(r,'targets')),routes:metric('WR',r=>present(r,'routes')),tprr:metric('WR',r=>derived(r,'tprr')),yprr:metric('WR',r=>derived(r,'yprr')),redZone:metric('WR',r=>present(r,'redZoneTargets')),trends:metric('WR',trends)},TE:{targets:metric('TE',r=>present(r,'targets')),routes:metric('TE',r=>present(r,'routes')),tprr:metric('TE',r=>derived(r,'tprr')),yprr:metric('TE',r=>derived(r,'yprr')),redZone:metric('TE',r=>present(r,'redZoneTargets')),trends:metric('TE',trends)},QB:{passing:metric('QB',r=>present(r,'passAttempts')),rushing:metric('QB',r=>present(r,'rushingAttempts')),efficiency:metric('QB',r=>derived(r,'yardsPerAttempt')),scrambles:metric('QB',r=>present(r,'scrambles')),designedRushes:metric('QB',r=>present(r,'designedRushes')),redZoneRushing:metric('QB',r=>present(r,'redZoneRushingAttempts')),trends:metric('QB',trends)}}};
if(require.main===module)console.log(JSON.stringify(report,null,2));module.exports=report;
