'use strict';
const fs=require('fs'),path=require('path'),{createHarness}=require('../tests/recommendation-baseline-harness.js');
const ROOT=path.resolve(__dirname,'..'),oldSnapshot=require('../data/rankings/fantasyland_2026-08-08.normalized.json'),newSnapshot=require('../data/rankings/fantasyland_draftday_2026-08-23.normalized.json');
const oldById=new Map(oldSnapshot.records.filter(row=>row.playerId!=null).map(row=>[String(row.playerId),row])),newById=new Map(newSnapshot.records.filter(row=>row.importStatus==='MATCHED').map(row=>[String(row.playerId),row]));
const oldHarness=createHarness({unified:true}),newHarness=createHarness({unified:true});oldHarness.applyRankingSnapshot(oldSnapshot.records);newHarness.applyRankingSnapshot(newSnapshot.records);
const halfFixtures=[
  {name:'half-opening-slot-1',pick:1,userSlot:1},{name:'half-opening-slot-5',pick:1,userSlot:5},{name:'half-opening-slot-10',pick:1,userSlot:10},
  {name:'half-middle-pick-47',pick:47,userSlot:7,userRoster:['Jahmyr Gibbs','CeeDee Lamb','Josh Allen','Trey McBride'],preserve:['Jauan Jennings','Oronde Gadsden II']},
  {name:'half-late-pick-107',pick:107,userSlot:7,userRoster:['Jahmyr Gibbs','James Cook','CeeDee Lamb','Puka Nacua','Josh Allen','Trey McBride','Chris Olave','DK Metcalf','David Montgomery','Jaylen Waddle'],preserve:['Jauan Jennings','Oronde Gadsden II']},
];
function configure(h,fixture){h.configure(fixture);return h.decisionRows(5)}
const scenarios=halfFixtures.map(fixture=>{const oldRows=configure(oldHarness,fixture),newRows=configure(newHarness,fixture),oldTop=oldRows[0],newTop=newRows[0],oldSource=oldById.get(String(newTop.id)),newSource=newById.get(String(newTop.id)),previousWinnerNewSource=newById.get(String(oldTop.id)),changed=String(oldTop.id)!==String(newTop.id);let classification='unchanged';if(changed){const inheritedImpossibleFall=Number(oldTop.sourceRank)<=Number(fixture.pick)-20&&Number(newTop.sourceRank)>=Number(fixture.pick)-20,newImproved=oldSource&&newSource&&Number(newSource.overallRank)<Number(oldSource.overallRank),oldWorsened=previousWinnerNewSource&&Number(previousWinnerNewSource.overallRank)>Number(oldTop.sourceRank);classification=inheritedImpossibleFall?'expected_due_to_fail_soft_snapshot_coverage':newImproved||oldWorsened?'expected_due_to_source_rank_movement':'questionable'}return{name:fixture.name,pick:fixture.pick,slot:fixture.userSlot,oldTopFive:oldRows,newTopFive:newRows,recommendationChanged:changed,classification,newWinnerSource:{oldRank:oldSource?.overallRank??null,newRank:newSource?.overallRank??null,oldTier:oldSource?.overallTier??null,newTier:newSource?.overallTier??null}}});
const fullSettings={teams:10,scoring:'full',receptions:1,passTD:6,startQB:1,startRB:1,startWR:2,startTE:1,flex:2,startK:1,startDST:1,bench:6,ir:1};
const full={name:'full-ppr-flex-pick-30',pick:30,oldTopFive:oldHarness.configureLeagueState({settings:fullSettings,currentPick:30,userSlot:10,userRoster:['Jahmyr Gibbs','CeeDee Lamb']}).topFive,newTopFive:newHarness.configureLeagueState({settings:fullSettings,currentPick:30,userSlot:10,userRoster:['Jahmyr Gibbs','CeeDee Lamb']}).topFive};full.recommendationChanged=String(full.oldTopFive[0].id)!==String(full.newTopFive[0].id);full.classification=full.recommendationChanged&&Number(full.oldTopFive[0].sourceRank)<=full.pick-20&&Number(full.newTopFive[0].sourceRank)>=full.pick-20?'expected_due_to_fail_soft_snapshot_coverage':full.recommendationChanged?'questionable':'unchanged';
const earlyLeak=scenarios.filter(row=>row.pick<=107).flatMap(row=>row.newTopFive).filter(row=>['K','DST'].includes(row.pos)),regressionNames=new Set(scenarios.filter(row=>row.pick<=107).flatMap(row=>row.newTopFive.map(item=>item.name)).filter(name=>name==='Jauan Jennings'||name==='Oronde Gadsden II')),duplicateVisibleCards=[...scenarios.map(row=>row.newTopFive),full.newTopFive].reduce((count,rows)=>count+(rows.length-new Set(rows.map(row=>String(row.id))).size),0);
const report={snapshotId:'2026-draftday-2026-08-23',generatedAt:new Date().toISOString(),boundedCanaries:scenarios,fullPprCanary:full,summary:{scenarios:scenarios.length+1,recommendationChanges:scenarios.filter(row=>row.recommendationChanged).length+(full.recommendationChanged?1:0),questionableChanges:scenarios.filter(row=>row.classification==='questionable').length+(full.classification==='questionable'?1:0),earlySpecialistLeakage:earlyLeak.length,JenningsOrGadsdenEarlyCards:[...regressionNames],duplicateVisibleCards}};
const output=path.join(ROOT,'outputs/player_audit/draftday_rankings_canary_2026-08-23.json');fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.summary));if(report.summary.questionableChanges||report.summary.earlySpecialistLeakage||report.summary.JenningsOrGadsdenEarlyCards.length)process.exit(1);
