'use strict';
const fs=require('fs'),path=require('path');
const {createHarness}=require('../tests/recommendation-baseline-harness.js');
const ROOT=path.resolve(__dirname,'..'),slots=[1,7,10],runs=[];
const average=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const distribution=values=>values.reduce((memo,value)=>(memo[value]=(memo[value]||0)+1,memo),{});
for(const slot of slots)for(let iteration=1;iteration<=5;iteration+=1){
  const result=createHarness({unified:true}).runDeterministicMock(slot),positionOrdinals={};let wr5Plus=0,rb4Plus=0;
  const selections=result.userSelections.map(row=>{const ordinal=(positionOrdinals[row.pos]||0)+1;positionOrdinals[row.pos]=ordinal;if(row.pos==='WR'&&ordinal>=5)wr5Plus+=1;if(row.pos==='RB'&&ordinal>=4)rb4Plus+=1;return{pick:row.pick,name:row.name,pos:row.pos,positionOrdinal:ordinal,sourceRank:row.sourceRank,corridor:row.debug?.strategy?.corridor,marginalUtility:row.debug?.strategy?.marginalUtility,integrity:row.debug?.strategy?.integrity}}),outside=selections.filter(row=>row.corridor?.inside===false),unexplained=outside.filter(row=>!row.corridor?.justification||row.corridor.justification==='UNEXPLAINED_REACH'),unsupported=selections.filter(row=>row.integrity?.unsupportedSaturation),poorGrade=result.grade.categories.draftValue.grade.startsWith('D')||result.grade.categories.draftValue.grade==='F'||result.grade.categories.positionalTiming.grade.startsWith('D')||result.grade.categories.positionalTiming.grade==='F';
  const timing=position=>selections.find(row=>row.pos===position)?.pick??null;
  runs.push({slot,iteration,roster:result.roster,selections,starterRanks:Object.fromEntries(result.finalState.starters.filter(row=>row.player).map(row=>[row.slot,row.player.fantasylandOverallRank??null])),timing:{QB:timing('QB'),TE:timing('TE'),K:timing('K'),DST:timing('DST')},wr5Plus,rb4Plus,outsideCorridor:outside.length,unexplainedReaches:unexplained.length,unsupportedSaturationSelections:unsupported.length,grade:{overall:result.grade.grade,draftValue:result.grade.categories.draftValue.grade,draftValueScore:result.grade.categories.draftValue.score,positionalTiming:result.grade.categories.positionalTiming.grade,positionalTimingScore:result.grade.categories.positionalTiming.score,averageValueDelta:result.grade.debug.averageValueDelta},recommenderGraderContradiction:unsupported.length>0||(poorGrade&&unexplained.length>0)});
}
const timingValues=position=>runs.map(run=>run.timing[position]).filter(Number.isFinite),countValues=position=>runs.map(run=>run.roster[position]||0),starterValues=slot=>runs.map(run=>run.starterRanks[slot]).filter(Number.isFinite);
const report={generatedAt:new Date().toISOString(),configuration:{teams:10,scoring:'half-PPR',quarterback:'one-QB',runs:runs.length,slots,runsPerSlot:5},aggregate:{completedRosters:runs.filter(run=>Object.values(run.roster).reduce((sum,value)=>sum+value,0)===17).length,averagePositionCounts:Object.fromEntries(['QB','RB','WR','TE','K','DST'].map(position=>[position,average(countValues(position))])),averageTiming:Object.fromEntries(['QB','TE','K','DST'].map(position=>[position,average(timingValues(position))])),wr5PlusSelections:runs.reduce((sum,run)=>sum+run.wr5Plus,0),rb4PlusSelections:runs.reduce((sum,run)=>sum+run.rb4Plus,0),averageStarterRanks:Object.fromEntries(['QB','RB1','RB2','WR1','WR2','WR3','TE','FLEX1','FLEX2'].map(slotName=>[slotName,average(starterValues(slotName))])),outsideCorridorSelections:runs.reduce((sum,run)=>sum+run.outsideCorridor,0),unexplainedReaches:runs.reduce((sum,run)=>sum+run.unexplainedReaches,0),unsupportedSaturationSelections:runs.reduce((sum,run)=>sum+run.unsupportedSaturationSelections,0),recommenderGraderContradictions:runs.filter(run=>run.recommenderGraderContradiction).length,draftValueGrades:distribution(runs.map(run=>run.grade.draftValue)),positionalTimingGrades:distribution(runs.map(run=>run.grade.positionalTiming))},runs};
const output=path.join(ROOT,'outputs/player_audit/jonin_4_3_1_full_mock_report.json');fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({output,aggregate:report.aggregate,representative:Object.fromEntries(slots.map(slot=>[slot,runs.find(run=>run.slot===slot)]))},null,2));
