'use strict';
const fs=require('fs'),path=require('path');
const {createHarness}=require('../tests/recommendation-baseline-harness.js');
const slots=[1,7,10],required={QB:1,RB:2,WR:3,TE:1,K:1,DST:1};
const average=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const timing=(selections,position)=>selections.find(row=>row.pos===position)?.pick??null;
function summarizeRun(ownerSlot,result){
  const selections=result.selections.filter(row=>row.team===ownerSlot),grade=result.grades.find(row=>Number(row.teamId)===ownerSlot),team=result.teams.find(row=>row.teamId===ownerSlot),ranked=selections.filter(row=>Number.isFinite(row.sourceRank)),premiums=ranked.map(row=>row.sourceRank-row.pick),material=selections.filter(row=>['MATERIAL_REACH','EXTREME_REACH'].includes(row.debug?.strategy?.priceOfAcquisition?.band)),requiredCompletion=row=>row.debug?.completion?.requiredPositions?.includes(row.pos),unexplained=selections.filter(row=>(row.debug?.strategy?.priceOfAcquisition?.unsupported||row.debug?.strategy?.priceOfAcquisition?.blocked)&&!requiredCompletion(row)),byPosition=position=>selections.filter(row=>row.pos===position);
  return {slot:ownerSlot,firstSeven:selections.slice(0,7).map(row=>({pick:row.pick,name:row.name,pos:row.pos,sourceRank:row.sourceRank})),roster:team.counts,rbFoundation:byPosition('RB').slice(0,2).map(row=>({name:row.name,sourceRank:row.sourceRank,tier:row.debug?.source?.overallTier,role:row.debug?.strategy?.role})),wrFoundation:byPosition('WR').slice(0,2).map(row=>({name:row.name,sourceRank:row.sourceRank,tier:row.debug?.source?.overallTier,role:row.debug?.strategy?.role})),timing:{QB:timing(selections,'QB'),TE:timing(selections,'TE'),K:timing(selections,'K'),DST:timing(selections,'DST')},averageAcquisitionPremium:average(premiums),averagePositiveReach:average(premiums.filter(value=>value>0)),materialReaches:material.map(row=>({pick:row.pick,name:row.name,reach:row.sourceRank-row.pick,band:row.debug.strategy.priceOfAcquisition.band,signals:row.debug.strategy.priceOfAcquisition.signals})),unexplainedReaches:unexplained.map(row=>({pick:row.pick,name:row.name,reach:row.sourceRank-row.pick,reasons:row.debug.strategy.integrity.reasons})),grade:{overall:grade.grade,score:grade.overallScore,draftValue:grade.categories.draftValue,positionalTiming:grade.categories.positionalTiming,benchUpside:grade.categories.benchUpside,rosterConstruction:grade.categories.rosterConstruction,leagueFit:grade.categories.leagueFit}};
}
function summarizeAllTeams(result){
  const rows=result.teams.map(team=>{const missing=Object.entries(required).filter(([position,count])=>(team.counts[position]||0)<count).map(([position])=>position),skillCount=(team.counts.RB||0)+(team.counts.WR||0)+(team.counts.TE||0),flexMissing=skillCount<8;return{teamId:team.teamId,managerName:team.managerName,counts:team.counts,missing,flexMissing,complete:!missing.length&&!flexMissing&&team.players.length===17,duplicateK:Math.max(0,(team.counts.K||0)-1),duplicateDST:Math.max(0,(team.counts.DST||0)-1),extremeSaturation:(team.counts.RB||0)>=8||(team.counts.WR||0)>=9}}),leakage=result.selections.filter(row=>(row.team===result.ownerSlot)!==row.personalized);
  return {teams:rows,completedRosters:rows.filter(row=>row.complete).length,missingQB:rows.filter(row=>row.missing.includes('QB')).length,missingTE:rows.filter(row=>row.missing.includes('TE')).length,missingK:rows.filter(row=>row.missing.includes('K')).length,missingDST:rows.filter(row=>row.missing.includes('DST')).length,missingFlex:rows.filter(row=>row.flexMissing).length,duplicateK:rows.reduce((sum,row)=>sum+row.duplicateK,0),duplicateDST:rows.reduce((sum,row)=>sum+row.duplicateDST,0),extremeSaturation:rows.filter(row=>row.extremeSaturation).length,rosterStateLeakage:leakage.map(row=>({pick:row.pick,team:row.team,personalized:row.personalized}))};
}
function auditRealFixture(){
  const h=createHarness({unified:true}),opening=["De'Von Achane",'Saquon Barkley','Trey McBride','Tetairoa McMillan','D.J. Moore','Terry McLaurin','Jaxson Dart'],late=['J.K. Dobbins','K.C. Concepcion',"Wan'Dale Robinson",'Woody Marks','Xavier Worthy','Rashid Shaheed'],picks=[74,87,94,107,114,127],rows=[];
  const apostrophe=h.resolvePlayerIdentity("Wan'Dale Robinson"),canonical=h.resolvePlayerIdentity('Wandale Robinson');
  if(!apostrophe||!canonical||String(apostrophe.id)!==String(canonical.id))throw new Error('Historical Wandale identity aliases did not resolve to one canonical player ID.');
  for(let index=0;index<late.length;index++){const target=late[index],identity=h.resolvePlayerIdentity(target),roster=[...opening,...late.slice(0,index)];if(!identity)throw new Error('Historical fixture identity was not found: '+target);h.configure({pick:picks[index],userSlot:7,userRoster:roster,preserve:[identity]});const debug=h.decisionDebug(identity),top=h.decisionRows(1)[0];rows.push({pick:picks[index],requestedName:target,playerId:identity.id,canonicalName:identity.name,normalizedIdentity:identity.normalizedIdentity,sourceRank:debug.source.overallRank,reach:debug.source.overallRank==null?null:debug.source.overallRank-picks[index],expectedSurvival:debug.strategy?.priceOfAcquisition?.survival,tier:debug.source.overallTier,role:debug.strategy?.role,marginalUtility:debug.strategy?.marginalUtility,benchOptionality:debug.strategy?.benchPortfolio,priceOfAcquisition:debug.strategy?.priceOfAcquisition,orderingRank:debug.finalOrderingRank,topRecommendation:top?{id:top.id,name:top.name,pos:top.pos,sourceRank:top.sourceRank,score:top.finalDecisionScore}:null,decision:debug.finalOrderingRank===1?'REMAINS_TOP_RECOMMENDATION':'NO_LONGER_BEATS_AVAILABLE_ALTERNATIVES',reasons:debug.strategy?.integrity?.reasons||[]})}
  return {aliasCheck:{historical:apostrophe,canonical,samePlayerId:true},rows};
}
if(process.argv.includes('--identity-only')){const audit=auditRealFixture();console.log(JSON.stringify(audit.aliasCheck));process.exit(0)}
if(process.argv.includes('--audit-only')){const audit=auditRealFixture(),output=path.resolve(__dirname,'../outputs/player_audit/jonin_4_3_2_real_fixture_audit.json');fs.writeFileSync(output,JSON.stringify({generatedAt:new Date().toISOString(),...audit},null,2)+'\n');console.log(JSON.stringify({output,...audit},null,2));process.exit(0)}
const runs=[];
const checkpoint=path.resolve(__dirname,'../outputs/player_audit/jonin_4_3_2_full_mock_checkpoint.json');
for(const slot of slots){const harness=createHarness({unified:true}),result=harness.runBlindAllManagerMock(slot);runs.push({gerard:summarizeRun(slot,result),allTeams:summarizeAllTeams(result)});fs.writeFileSync(checkpoint,JSON.stringify({generatedAt:new Date().toISOString(),status:'IN_PROGRESS',completedSlots:runs.map(row=>row.gerard.slot),runs},null,2)+'\n')}
const aggregate={completedRosters:runs.reduce((sum,row)=>sum+row.allTeams.completedRosters,0),teamRosters:runs.length*10,missingQB:runs.reduce((sum,row)=>sum+row.allTeams.missingQB,0),missingTE:runs.reduce((sum,row)=>sum+row.allTeams.missingTE,0),missingK:runs.reduce((sum,row)=>sum+row.allTeams.missingK,0),missingDST:runs.reduce((sum,row)=>sum+row.allTeams.missingDST,0),missingFlex:runs.reduce((sum,row)=>sum+row.allTeams.missingFlex,0),duplicateK:runs.reduce((sum,row)=>sum+row.allTeams.duplicateK,0),duplicateDST:runs.reduce((sum,row)=>sum+row.allTeams.duplicateDST,0),extremeSaturation:runs.reduce((sum,row)=>sum+row.allTeams.extremeSaturation,0),rosterStateLeakage:runs.reduce((sum,row)=>sum+row.allTeams.rosterStateLeakage.length,0),unexplainedGerardReaches:runs.reduce((sum,row)=>sum+row.gerard.unexplainedReaches.length,0)};
const fixtureAudit=auditRealFixture(),report={generatedAt:new Date().toISOString(),version:'Jōnin 4.3.2 candidate',configuration:{teams:10,scoring:'half-PPR',quarterback:'one-QB',fullMocks:3,slots},beforePick7Fixture:{opening:["De'Von Achane",'Saquon Barkley','Trey McBride','Tetairoa McMillan','D.J. Moore','Terry McLaurin','Jaxson Dart'],later:['J.K. Dobbins','K.C. Concepcion',"Wan'Dale Robinson",'Woody Marks','Xavier Worthy','Rashid Shaheed'],overallGrade:'B',draftValue:'D',positionalTiming:'C-',averagePremium:11.3,reachesAtLeastSix:8},aggregate,runs,identityAliasCheck:fixtureAudit.aliasCheck,realFixtureAcquisitionAudit:fixtureAudit.rows};
const output=path.resolve(__dirname,'../outputs/player_audit/jonin_4_3_2_full_mock_report.json');fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({output,aggregate,runs:runs.map(row=>({slot:row.gerard.slot,firstSeven:row.gerard.firstSeven,roster:row.gerard.roster,averageAcquisitionPremium:row.gerard.averageAcquisitionPremium,materialReaches:row.gerard.materialReaches.length,unexplainedReaches:row.gerard.unexplainedReaches.length,grade:row.gerard.grade,allTeams:{completedRosters:row.allTeams.completedRosters,missingQB:row.allTeams.missingQB,missingTE:row.allTeams.missingTE,missingK:row.allTeams.missingK,missingDST:row.allTeams.missingDST,duplicateK:row.allTeams.duplicateK,duplicateDST:row.allTeams.duplicateDST,extremeSaturation:row.allTeams.extremeSaturation,rosterStateLeakage:row.allTeams.rosterStateLeakage.length}}))},null,2));
fs.writeFileSync(checkpoint,JSON.stringify({generatedAt:new Date().toISOString(),status:'COMPLETE',completedSlots:slots,report:output},null,2)+'\n');
