#!/usr/bin/env node
'use strict';

const fs=require('node:fs');
const path=require('node:path');
const Harness=require('../tests/recommendation-baseline-harness');
const ROOT=path.resolve(__dirname,'..'),OUTPUT=path.join(ROOT,'outputs/championship_equity/production_canary_4_3_20.json');
const middleRoster=['Puka Nacua','Christian McCaffrey','Josh Allen','Trey McBride','Chris Olave','James Cook'];
const lateRoster=['Josh Allen','Christian McCaffrey','James Cook','Puka Nacua','CeeDee Lamb','Chris Olave','Brock Bowers','DK Metcalf','David Montgomery','Jaylen Waddle','Tetairoa McMillan','Jordan Addison'];
const completionRoster=[...lateRoster,'Dak Prescott','Tony Pollard','Rashid Shaheed'];
const turnPick=(round,slot)=>round%2?((round-1)*10+slot):(round*10-slot+1);
function capture(harness,{slot,round,roster=[]}){harness.configureFresh({pick:1,slot});harness.configure({pick:turnPick(round,slot),userSlot:slot,userRoster:roster});harness.setChampionshipEquityEnabled(false);const off=harness.championshipEquityCanary();harness.setChampionshipEquityEnabled(true);const on=harness.championshipEquityCanary(),offIds=off.topFive.map(row=>row.id),onIds=on.topFive.map(row=>row.id),differences=on.topFive.map((row,index)=>row.id===off.topFive[index]?.id?null:Object.freeze({rank:index+1,off:off.topFive[index]?.name??null,on:row.name,offTier:off.topFive[index]?.tier??null,onTier:row.tier})).filter(Boolean);return Object.freeze({slot,round,pick:on.pick,off,on,differences:Object.freeze(differences),orderingStable:JSON.stringify(offIds)===JSON.stringify(onIds)})}
function build(){const harness=Harness.createHarness({unified:true}),states=[];for(const slot of [1,5,10]){states.push(capture(harness,{slot,round:1}),capture(harness,{slot,round:2,roster:['Bijan Robinson']}),capture(harness,{slot,round:3,roster:['Bijan Robinson','Puka Nacua']}),capture(harness,{slot,round:7,roster:middleRoster}),capture(harness,{slot,round:13,roster:lateRoster}),capture(harness,{slot,round:16,roster:completionRoster}))}const tierOrder=['S','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O'],hardReachCount=states.reduce((sum,state)=>sum+state.differences.filter(row=>{const left=tierOrder.indexOf(row.offTier),right=tierOrder.indexOf(row.onTier);return left>=0&&right-left>1}).length,0),firstThree=states.filter(row=>row.round<=3),completion=states.filter(row=>row.round===16);return Object.freeze({schemaVersion:1,milestone:'Jōnin 4.3.20',label:'Bounded Championship Equity Production Canary',method:'Deterministic user-turn snapshots; no full mock loop.',profiles:Object.freeze(['primary-league']),slots:Object.freeze([1,5,10]),states:Object.freeze(states),summary:Object.freeze({pairedStates:states.length,earlyStates:firstThree.length,earlyOrderingStable:firstThree.every(row=>row.orderingStable),changedStates:states.filter(row=>!row.orderingStable).length,changedCardPositions:states.reduce((sum,row)=>sum+row.differences.length,0),hardReachCount,completionStates:completion.length,completionModes:Object.freeze([...new Set(completion.map(row=>row.on.completion.mode))]),completionPositionRecommendations:Object.freeze(completion.map(row=>Object.freeze({slot:row.slot,positions:row.on.topFive.map(item=>item.pos),requiredPositions:row.on.completion.requiredPositions})))})})}
function main(){const report=build(),temporary=`${OUTPUT}.tmp-${process.pid}`;fs.writeFileSync(temporary,`${JSON.stringify(report,null,2)}\n`);JSON.parse(fs.readFileSync(temporary,'utf8'));fs.renameSync(temporary,OUTPUT);console.log(JSON.stringify({output:OUTPUT,summary:report.summary,changes:report.states.filter(row=>row.differences.length).map(row=>({slot:row.slot,round:row.round,pick:row.pick,differences:row.differences,bestPick:row.on.bestPick}))},null,2));return report}
if(require.main===module)main();
module.exports=Object.freeze({turnPick,capture,build,main});
