#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),Production=require('../js/championship-equity-production-v1'),{createHarness}=require('../tests/recommendation-baseline-harness.js');
const ROOT=path.resolve(__dirname,'..'),OUTPUT=path.join(ROOT,'outputs/championship_equity/revalidation_4_3_21.json'),rankings=require('../data/rankings/fantasyland_draftday_2026-08-23.normalized.json'),flock=require('../data/rankings/flock_draftday_2026-08-23.normalized.json');
const traditional={teams:10,scoring:'half',receptions:.5,passTD:4,startQB:1,startRB:2,startWR:3,startTE:1,flex:2,startK:1,startDST:1,bench:6,ir:1},full={teams:10,scoring:'full',receptions:1,passTD:6,startQB:1,startRB:1,startWR:2,startTE:1,flex:2,startK:1,startDST:1,bench:6,ir:1};
const balanced=['Jahmyr Gibbs','Puka Nacua','Josh Allen','Trey McBride','Chris Olave','James Cook'],secure=['Josh Allen','Christian McCaffrey','James Cook','Puka Nacua','CeeDee Lamb','Chris Olave','Brock Bowers','DK Metcalf','David Montgomery','Jaylen Waddle','Tetairoa McMillan','Jordan Addison'],completion=[...secure,'Dak Prescott','Tony Pollard','Rashid Shaheed'];
const turnPick=(round,slot)=>round%2?((round-1)*10+slot):(round*10-slot+1),h=createHarness({unified:true});h.applyRankingSnapshot(rankings.records);
function compact(harness){const snapshot=harness.snapshot('capture'),decisions=harness.championshipEquityDecisions(),rows=harness.decisionRows(5),rowById=new Map(rows.map(row=>[String(row.id),row])),categoryById=new Map(decisions.topFive.map(row=>[String(row.id),row]));return{roster:snapshot.roster,topFive:snapshot.topFive.map(row=>{const debug=rowById.get(String(row.id))||{},category=categoryById.get(String(row.id))||{};return{id:String(row.id),name:row.name,pos:debug.pos||null,tier:row.decisionTier,sourceRank:debug.sourceRank??null,score:debug.displayScore??row.finalPickScore,category:category.label??null,evidence:category.evidence??null,acquisitionGap:(debug.sourceRank??0)-snapshot.currentPick,starterImpact:debug.starterImpact??null,integrity:debug.integrity??null}}),bestPick:decisions.bestPick,highestUpside:decisions.highestUpside}}
function capture(scenario){h.configureLeagueState({settings:scenario.settings||traditional,currentPick:scenario.pick,userSlot:scenario.slot,userRoster:scenario.roster||[],preserve:scenario.preserve||[]});h.setChampionshipEquityEnabled(false);const off=compact(h);h.setChampionshipEquityEnabled(true);const on=compact(h);h.setChampionshipEquityEnabled(false);const rolledBack=compact(h),offIds=off.topFive.map(row=>row.id),onIds=on.topFive.map(row=>row.id),offBest=off.topFive.find(row=>row.category==='Best Pick')||off.topFive[0],onBest=on.topFive.find(row=>row.category==='Best Pick')||on.topFive[0],offUpside=off.topFive.find(row=>row.category==='Highest Upside'),onUpside=on.topFive.find(row=>row.category==='Highest Upside'),offValue=off.topFive.find(row=>row.category==='Best Value'),onValue=on.topFive.find(row=>row.category==='Best Value'),changed=JSON.stringify(offIds)!==JSON.stringify(onIds),tierOrder=['S','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O'],tierGap=tierOrder.indexOf(onBest.tier)-tierOrder.indexOf(offBest.tier),hardReach=changed&&Number(onBest.acquisitionGap)>18,starterViolation=changed&&scenario.remainingStarterCapacity>0&&Number(onBest.starterImpact)<Number(offBest.starterImpact),unsupportedInfluence=changed&&(['QB','TE'].includes(onBest.pos)||onBest.evidence?.status!=='SUPPORTED'),completionState=scenario.phase==='COMPLETION'?h.completionSnapshot().state:null,completionFailure=completionState?.mode==='HARD'&&!completionState.requiredPositions.includes(onBest.pos),rollbackRestored=JSON.stringify(off.topFive)===JSON.stringify(rolledBack.topFive);return{...scenario,off,on,orderingChanged:changed,bestPickChanged:offBest.id!==onBest.id,highestUpsideChanged:(offUpside?.id||null)!==(onUpside?.id||null),bestValueChanged:(offValue?.id||null)!==(onValue?.id||null),tierGap,crossTierPromotion:changed&&tierGap!==0,hardReach,starterViolation,unsupportedInfluence,completionState,completionFailure,rollbackRestored}}
const scenarios=[];
for(const slot of [1,2,4,5,7,10])scenarios.push({name:`opening-slot-${slot}`,phase:'EARLY',slot,pick:slot,round:1,roster:[],remainingStarterCapacity:9});
for(const slot of [1,5,10])scenarios.push({name:`round-2-slot-${slot}`,phase:'EARLY',slot,pick:turnPick(2,slot),round:2,roster:['Bijan Robinson'],remainingStarterCapacity:8});
for(const slot of [2,7,10])scenarios.push({name:`round-3-slot-${slot}`,phase:'EARLY',slot,pick:turnPick(3,slot),round:3,roster:['Bijan Robinson','Puka Nacua'],remainingStarterCapacity:7});
scenarios.push(
  {name:'middle-no-rb',phase:'MIDDLE',slot:1,pick:61,round:7,roster:['Puka Nacua','CeeDee Lamb','Chris Olave','Josh Allen','Trey McBride','DK Metcalf'],remainingStarterCapacity:3},
  {name:'middle-no-wr',phase:'MIDDLE',slot:4,pick:64,round:7,roster:['Jahmyr Gibbs','Bijan Robinson','James Cook','Josh Allen','Trey McBride','David Montgomery'],remainingStarterCapacity:3},
  {name:'known-good-pick-61',phase:'MIDDLE',slot:1,pick:61,round:7,roster:balanced,remainingStarterCapacity:2,preserve:['Jameson Williams','Brian Thomas Jr.']},
  {name:'round-7-te-need',phase:'MIDDLE',slot:7,pick:67,round:7,roster:['Jahmyr Gibbs','James Cook','Puka Nacua','CeeDee Lamb','Chris Olave','Josh Allen'],remainingStarterCapacity:2,preserve:['Harold Fannin Jr.','Tucker Kraft','Sam LaPorta','George Kittle','Oronde Gadsden II']},
  {name:'late-hero-rb',phase:'LATE',slot:2,pick:99,round:10,roster:['Jahmyr Gibbs','Puka Nacua','CeeDee Lamb','Chris Olave','Josh Allen','Trey McBride','DK Metcalf','Jaylen Waddle','Jordan Addison'],remainingStarterCapacity:0},
  {name:'late-strong-rb-weak-wr',phase:'LATE',slot:5,pick:96,round:10,roster:['Jahmyr Gibbs','Bijan Robinson','James Cook','David Montgomery','Josh Allen','Trey McBride','Puka Nacua','Chris Olave','Tony Pollard'],remainingStarterCapacity:1},
  {name:'late-strong-wr-weak-rb',phase:'LATE',slot:10,pick:91,round:10,roster:['Jahmyr Gibbs','Puka Nacua','CeeDee Lamb','Chris Olave','DK Metcalf','Jaylen Waddle','Josh Allen','Trey McBride','Jordan Addison'],remainingStarterCapacity:1},
  {name:'bench-round-11',phase:'BENCH',slot:1,pick:101,round:11,roster:secure.slice(0,10),remainingStarterCapacity:0},
  {name:'bench-round-12',phase:'BENCH',slot:7,pick:114,round:12,roster:secure.slice(0,11),remainingStarterCapacity:0},
  {name:'live-style-late-cluster',phase:'BENCH',slot:1,pick:121,round:13,roster:secure,remainingStarterCapacity:0,preserve:["Wan'Dale Robinson",'K.C. Concepcion','Jonah Coleman','Brian Robinson Jr.']},
  {name:'bench-round-14-full-ppr',phase:'BENCH',slot:7,pick:134,round:14,settings:full,roster:secure,remainingStarterCapacity:0},
  {name:'completion-slot-1',phase:'COMPLETION',slot:1,pick:turnPick(16,1),round:16,roster:completion,remainingStarterCapacity:0},
  {name:'completion-slot-5',phase:'COMPLETION',slot:5,pick:turnPick(16,5),round:16,roster:completion,remainingStarterCapacity:0},
  {name:'completion-slot-10',phase:'COMPLETION',slot:10,pick:turnPick(16,10),round:16,roster:completion,remainingStarterCapacity:0}
);
const states=scenarios.map(capture),count=predicate=>states.filter(predicate).length,sourceDisagreements=rankings.records.filter(row=>row.importStatus==='MATCHED').map(row=>{const other=flock.records.find(item=>item.importStatus==='MATCHED'&&item.playerId===row.playerId);return other&&{playerId:row.playerId,name:row.canonicalPlayerName,fantasyland:{rank:row.overallRank,tier:row.overallTier},flock:{rank:other.overallRank,tier:other.overallTier}}}).filter(row=>row&&(row.fantasyland.rank!==row.flock.rank||row.fantasyland.tier!==row.flock.tier));
Production.setEnabled(true);const attackEvidence=(score,classification='HIGH')=>({status:'SUPPORTED',score,classification,evidenceComplete:true}),attackRow=(id,tier,rank,score)=>({id,position:'WR',tier,rank,mamba:80,sourceValue:40,evidence:attackEvidence(score),starterImpact:0,survival:'UNLIKELY_TO_SURVIVE'}),oneTier=Production.sameTierDecision({incumbent:attackRow('a','A',50,40),challenger:attackRow('b','B',51,99),context:{draftStage:'LATE',remainingStarterCapacity:0}}),multiTier=Production.sameTierDecision({incumbent:attackRow('a','A',50,40),challenger:attackRow('b','C',51,99),context:{draftStage:'LATE',remainingStarterCapacity:0}});
const known=states.find(row=>row.name==='known-good-pick-61'),te=states.find(row=>row.name==='round-7-te-need'),live=states.find(row=>row.name==='live-style-late-cluster'),report={schemaVersion:1,milestone:'Jōnin 4.3.21',snapshotId:'2026-draftday-2026-08-23',method:'Bounded deterministic paired recommendation states; no full mock loop.',states,attacks:{oneTier,multiTier},sourceDisagreement:{count:sourceDisagreements.length,sample:sourceDisagreements.slice(0,12)},knownGoodRevalidation:{off:known.off.topFive,on:known.on.topFive,bestPickDecision:known.on.bestPick},teTiming:{off:te.off.topFive,on:te.on.topFive},liveStyleLateCluster:{off:live.off.topFive,on:live.on.topFive},summary:{pairedStates:states.length,earlyStates:count(row=>row.phase==='EARLY'),middleStates:count(row=>row.phase==='MIDDLE'),lateStates:count(row=>row.phase==='LATE'),benchStates:count(row=>row.phase==='BENCH'),completionStates:count(row=>row.phase==='COMPLETION'),recommendationOrderChanges:count(row=>row.orderingChanged),bestPickChanges:count(row=>row.bestPickChanged),highestUpsideChanges:count(row=>row.highestUpsideChanged),earlyChanges:count(row=>row.phase==='EARLY'&&row.orderingChanged),crossTierAttempts:2,crossTierPromotions:count(row=>row.crossTierPromotion),hardReachesIntroduced:count(row=>row.hardReach),starterFoundationViolations:count(row=>row.starterViolation),heroRbViolations:states.filter(row=>row.name==='late-hero-rb'&&row.starterViolation).length,kDstCompletionFailures:count(row=>row.completionFailure),incompleteEvidenceInfluence:count(row=>row.unsupportedInfluence&&row.on.topFive[0]?.evidence?.status==='INCOMPLETE_EVIDENCE'),unsupportedQbTeInfluence:count(row=>row.unsupportedInfluence&&['QB','TE'].includes(row.on.topFive[0]?.pos)),bestValueChanges:count(row=>row.bestValueChanged),oneTierAction:oneTier.action,multiTierAction:multiTier.action}};
const rollbackStates=states.map(state=>({name:state.name,restored:state.rollbackRestored}));report.rollback={states:rollbackStates.length,restored:rollbackStates.every(row=>row.restored)};
fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.summary));const critical=['earlyChanges','crossTierPromotions','hardReachesIntroduced','starterFoundationViolations','heroRbViolations','kDstCompletionFailures','incompleteEvidenceInfluence','unsupportedQbTeInfluence','bestValueChanges'];if(critical.some(key=>report.summary[key]!==0)||oneTier.eligible||multiTier.eligible)process.exit(1);
