#!/usr/bin/env node
'use strict';
const Health=require('../js/data-health-v1.js'),Profiles=require('../js/league-profiles-v1.js'),Session=require('../js/draft-session-v1.js'),Workflow=require('../js/draft-workflow-v1.js'),MathV1=require('../js/draft-math-v1.js'),Completion=require('../js/roster-completion-constraint-v1.js'),Injuries=require('../js/sleeper-injury-adapter-v1.js'),CE=require('../js/championship-equity-production-v1.js'),{createHarness}=require('../tests/recommendation-baseline-harness.js');
const rankings=require('../data/rankings/fantasyland_draftday_2026-08-23.normalized.json'),equity=require('../data/championship_equity_2026.json'),injurySnapshot=require('../data/injuries_2026.json');
const started=Date.now(),checks=[],check=(name,value)=>{if(!value)throw new Error(name);checks.push(name)},storage=()=>{const map=new Map();return{getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,String(value)),removeItem:key=>map.delete(key)}};
async function run(){
  check('active Fantasyland rankings',Health.validateRankingSnapshot(rankings,'Fantasyland').matched.length===256);const local=storage(),profiles=new Profiles.LeagueProfileStore(local,{draftSession:Session});profiles.initialize();check('league profile',profiles.active().settings.teams===10);
  const h=createHarness({unified:true});h.applyRankingSnapshot(rankings.records);h.configureFresh({pick:1,slot:10});const recommendationStarted=Date.now(),top=h.snapshot('draftday-smoke').topFive,recommendationMs=Date.now()-recommendationStarted;check('recommendations',top.length===5&&new Set(top.map(row=>String(row.id))).size===5);
  let excluded=Workflow.exclude([],top[0].id);check('exclude recommendation',Workflow.isExcluded(excluded,top[0].id));check('replacement recommendation',top.find(row=>!Workflow.isExcluded(excluded,row.id)).id===top[1].id);excluded=Workflow.restore(excluded,top[0].id);check('restore recommendation',!Workflow.isExcluded(excluded,top[0].id));
  CE.loadSnapshot(equity);CE.setEnabled(false);check('CE rollback',CE.isEnabled()===false);CE.setEnabled(true);check('CE activation',CE.isEnabled()===true);
  const draftStore=new Session.DraftSessionStore(local),history=[{pick:1,id:top[0].id,team:1}],base={status:'active',mode:'live',leagueProfileId:'primary-league',slot:10,pick:2,currentRound:1,currentPickOwner:2,drafted:[top[0].id],history,excludedRecommendationIds:[String(top[1].id)],settings:{teams:10,rosterSlots:['QB']},leagueConfiguration:{teams:10,totalRounds:1,totalPicks:10},managers:{}};draftStore.start(base);check('persistence and pick',draftStore.load().history.length===1&&draftStore.load().excludedRecommendationIds.length===1);draftStore.save({...base,pick:1,currentPickOwner:1,drafted:[],history:[]});check('undo',draftStore.load().history.length===0&&draftStore.load().excludedRecommendationIds.length===1);
  const activeExport=Workflow.buildExport({appVersion:'Jōnin 4.3.23',sessionId:'smoke',draftMode:'live',currentPick:2,currentRound:1,expectedTotalPicks:10,history:[{overallPick:1,canonicalPlayerId:String(top[0].id)}],excludedPlayerIds:[String(top[1].id)]});check('active JSON export',activeExport.draft.status==='active'&&activeExport.exclusions.canonicalPlayerIds.length===1);
  const previous={...injurySnapshot,cacheState:'CURRENT'},manager=Injuries.createManager({storage:local,now:()=> '2026-08-24T00:00:00Z',fetchFn:async()=>{throw new Error('offline')}});manager.prime(previous);const failed=await manager.refreshNow([]);check('injury fail-soft',failed.snapshot?.cacheState==='STALE'&&failed.snapshot.records.length===previous.records.length);
  const completion=Completion.buildState({rosterState:{starters:[{slot:'K',kind:'K',player:null},{slot:'DEF',kind:'DST',player:null}]},availablePlayers:[{id:'rb',pos:'RB'},{id:'k',pos:'K'},{id:'dst',pos:'DST'}],currentPick:1,totalPicks:2,userTeam:1,teamForPick:()=>1});check('K/DST completion',Completion.constrainPool([{id:'rb',pos:'RB'},{id:'k',pos:'K'},{id:'dst',pos:'DST'}],completion).every(player=>['K','DST'].includes(player.pos)));
  const teams=10,rounds=1,total=teams*rounds,finalHistory=Array.from({length:total},(_,index)=>({pick:index+1,id:`final-${index+1}`,team:MathV1.teamForPick(index+1,teams)})),complete=Session.createSnapshot({status:'complete',mode:'live',leagueProfileId:'primary-league',slot:10,pick:total+1,currentRound:2,currentPickOwner:null,drafted:finalHistory.map(row=>row.id),history:finalHistory,settings:{teams,rosterSlots:['BENCH1']},leagueConfiguration:{teams,totalRounds:rounds,totalPicks:total},managers:{}});check('final pick',complete.status==='complete'&&complete.pick===11);check('completed JSON export',Workflow.buildExport({draftMode:'live',currentPick:11,currentRound:2,expectedTotalPicks:10,history:finalHistory}).draft.status==='complete');
  CE.setEnabled(true);const runtimeMs=Date.now()-started,result={passCount:checks.length,checks,recommendationMs,runtimeMs,targetMs:30000,withinTarget:runtimeMs<30000};console.log(JSON.stringify(result));if(!result.withinTarget)process.exit(1);
}
run().catch(error=>{console.error(JSON.stringify({passCount:checks.length,error:error.message,runtimeMs:Date.now()-started}));process.exit(1)});
